### ISSUE TITLE
Config screen is blank.

### ISSUE THREAD

**Issue by richterlevania3** [mixxorz/Glass#52] opened 2020-08-23 00:16 UTC
Date: 2020-08-22 21:14:18
ID: 9
Error occured in: Global
Count: 1
Message: ...ty\Libs\AceGUI-3.0-SharedMediaWidgets\FontWidget.lua line 180:
   attempt to call method 'GetBaseFrame' (a nil value)
Debug:
   [string "=(tail call)"]: ?
   [string "@Rarity\Libs\AceGUI-3.0-SharedMediaWidgets\FontWidget.lua"]:180: ?()
   [string "@Glass\libs\AceGUI-3.0\AceGUI-3.0.lua"]:108:
      ...nterface\AddOns\Glass\libs\AceGUI-3.0\AceGUI-3.0.lua:97
   [string "@Glass\libs\AceGUI-3.0\AceGUI-3.0.lua"]:146: Create()
   [string "@Glass\libs\AceConfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua"]:1095:
      ...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1092
   [string "@Glass\libs\AceConfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua"]:1281:
      ...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1117
   [string "@Glass\libs\AceConfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua"]:1648: FeedGroup()
   [string "@Glass\libs\AceConfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua"]:1573:
      ...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1557
   [string "=[C]"]: ?
   [string "@Glass\libs\AceGUI-3.0\AceGUI-3.0.lua"]:72:
      ...nterface\AddOns\Glass\libs\AceGUI-3.0\AceGUI-3.0.lua:70
   [string "@Glass\libs\AceGUI-3.0\AceGUI-3.0.lua"]:306: Fire()
   [string "@Glass\libs\AceGUI-3.0\widgets\AceGUIContainer-TreeGroup.lua"]:526: Select()
   [string "@Glass\libs\AceGUI-3.0\widgets\AceGUIContainer-TreeGroup.lua"]:534: SelectByValue()
   [string "@Glass\libs\AceConfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua"]:1744: FeedGroup()
   [string "@Glass\libs\AceConfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua"]:1928: Open()
   [string "@Glass\Glass\Modules\Config.lua"]:236: ?()
   [string "@Bartender4\libs\AceConsole-3.0\AceConsole-3.0.lua"]:94: ?()
   [string "@..\FrameXML\ChatFrame.lua"]:4859: ChatEdit_ParseText()
   [string "@..\FrameXML\ChatFrame.lua"]:4523: ChatEdit_SendText()
   [string "@..\FrameXML\ChatFrame.lua"]:4559: ChatEdit_OnEnterPressed()
   [string "*:OnEnterPressed"]:1:
      [string "*:OnEnterPressed"]:1
Locals:
None
AddOns:
  Swatter, v8.2.6511 (SwimmingSeadragon)
  BagBrother, v
  Bagnon, v8.3.5
  Bartender4, v4.9.0
  BeanCounter, v8.2.6505 (SwimmingSeadragon)
  DejaCharacterStats, v830r306
  FasterLoot, v2.01
  GarrisonCommanderBroker, v3.2.4 1.1.0
  GatherMate2, v1.45.5
  Glass, v1.0.1
  HandyNotes, vv1.5.10
  HandyNotesArgus, vv0.15
  HandyNotesBrokenShore, vv1.33
  HandyNotesLegionRaresTreasures, v1.1
  HandyNotesLegionTreasures, v1
  HandyNotesMechagonAndNazjatar, v13
  Informant, v8.2.6508 (SwimmingSeadragon)
  MountJournalEnhanced, v2.7.2
  MoveAnything, v17.1.0
  MuteSoundFile, vv8.3.0
  Overachiever, v1.0.9
  OverachieverCache, v1.0.9
  PetJournalEnhanced, v2.9.30
  Rarity, v1.0 (r698-release)
  RarityOptions, v
  Recount, vv8.3.0d
  SavedInstances, v8.3.4
  Scrap, v8.3.2
  Stubby, v8.2.6510 (SwimmingSeadragon)
  TomCatsNazjatar, v01.04.06
  TomTom, vv80300-1.1.3
  ToyBoxEnhanced, v2.4.1
  TradeSkillMaster, vv4.9.38
  TradeSkillMasterAppHelper, vv4.0.8
  WoWGatheringNodes, vBFA-8.3-update-v1.0
  BlizRuntimeLib_enUS v8.3.7.80300 <none>
  (ck=411)

**Comment by Dairyman** [comment] 2020-08-24 20:59
Glass is missing the [AceGUI-3.0-SharedMediaWidgets](https://www.curseforge.com/wow/addons/ace-gui-3-0-shared-media-widgets) lib if you want to use the LSM30_Font dialogControl. And the first error seems be a broken AceGUI-3.0-SharedMediaWidgets.

**Comment by mixxorz** [comment] 2020-09-13 07:42
Recently fixed an issue with AceDB which might have been the cause of this. Closing this for now. We can reopen if this is still happening.

**Closed by mixxorz** 2020-09-13 07:42 UTC
Labels: bug
